# Generated by Django 5.1.5 on 2025-01-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphproject',
            name='edges',
        ),
        migrations.AddField(
            model_name='graphproject',
            name='edge',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='graphproject',
            name='vertex',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
